### PR TITLE
fixed logic for converting between radians/degrees for transformations

### PR DESCRIPTION
**Pull request by snowman2**
Attempt for #192 & #195 - needs work.

### CODE REVIEW

**Comment by jswhit** [comment]
I still don't understand what `proj_angular_output` does.  The docs says "Check if an operation returns angular output", but that's pretty vague.

**Comment by snowman2** [comment]
I am wondering if it is not working properly or I am missing something. Example usage: https://github.com/OSGeo/proj.4/blob/5dc01e985e86b441ba2a671b712d3b211c8a2b33/src/apps/proj.cpp#L144

**Comment by snowman2** [comment]
Looks like my logic is off there. I will tweak it this evening.

**Comment by snowman2** [comment]
Also, looks like CI/CD are not enabled for the new repo location,

**Comment by jswhit** [comment]
I think travis and appveyor should be activated now.

**Comment by snowman2** [comment]
@jswhit, if the tests pass, it should be good to merge in.

**Comment by jswhit** [comment]
OK, thanks @snowman2 !

**Comment by snowman2** [comment]
Not a problem. Fingers crossed it is stable 🤞

**Comment by jswhit** [comment]
Do you think we should release 2.1.0 soon?

**Comment by snowman2** [comment]
Yes, I do. I think there are some much needed fixes in the next version.

**Comment by jswhit** [comment]
OK, I'll make a release tag tomorrow.

**Comment by snowman2** [comment]
Sounds good. Also, the docs need to be rebuilt.

**Pull request merged**
