### PR TITLE
Remove cruft from unsupported software versions

### PR DESCRIPTION
**Pull request by micahcochran**
Remove cruft in unittest/test.py from supporting old Python and old PROJ versions.

### CODE REVIEW

**Comment by snowman2** [comment]
Looks good. Thoughts on adding a test to check the proj version string? Maybe a regex match?

Mostly thinking that as it was kinda tested in the pieces you are removing.

**Comment by micahcochran** [comment]
@snowman2 I'd try distutils.version either StrictVersion or LooseVersion to see how far you get with those.  Those work pretty well.  I'm not sure how fast they are, but that didn't matter so much because I was using them in unittest code.

Personally, regex would be my last resort.  Baring distutils, I might use some kind of proj_version_str.split('.')[0] comparison.  Or I might actually somehow cleaverly expose PROJ_VERSION_MAJOR and  PROJ_VERSION_MINOR from C, if it needed to be fast.

This PR has two goals, (1) get rid of some code needed for Python version below 2.6. If PROJ versions less than 5 are no longer supported, (2) there is no longer a reason to test for an RuntimeError exception created by the inverse of the Hammer projection, which is what was happening in the standard version of PROJ versions 4.9.2 and below.

**Comment by snowman2** [comment]
I definitely agree with your goals of the PR. I think it is nice to do some cleanup. Any methods for checking would be fine. Even just asserting it is there works for me.

**Comment by jswhit** [comment]
Agree that the place to check the Proj version is in setup.py.  However, build will fail with Proj < 6 anyway, so this is not critical.  Going to go ahead and merge.

**Comment by micahcochran** [comment]
Thanks.

**Pull request merged**
