### PR TITLE
release gil in core cython/PROJ code

### LINKED ISSUE #386: Release the GIL in core transformation code
See discussion in https://github.com/pyproj4/pyproj/pull/380#issuecomment-516365850.

By using `nogil` in cython we can ensure to release the GIL in the hot spots of the transformation code, which can ensure that other applications can use pyproj code in parallel (eg using dask)

### PR DESCRIPTION
**Pull request by snowman2**
- [x] Closes #386
 - [x] Fully documented, including `history.rst` for all changes and `api/*.rst` for new API

@jorisvandenbossche mind trying this out?

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@snowman2 Thanks a lot for looking into this!

I think we need to do some timings to check the overhead of releasing the GIL in single threaded cases (releasing/re-acquiring the GIL many times for tiny computations can give quite some overhead). 
(I can try to help with that, but that might take a few days)

**Comment by snowman2** [comment]
Looks fine to me:
```
In [1]: import numpy as np 
   ...: from pyproj import Transformer, transform                               

In [2]: transformer = Transformer.from_proj(2263, 4326) 
   ...: x_coords = np.random.randint(80000, 120000) 
   ...: y_coords = np.random.randint(200000, 250000)                            

In [3]: %timeit transform(2263, 4326, x_coords, y_coords)                       
63.9 ms ± 4.85 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [4]: %timeit transformer.transform(x_coords, y_coords)                       
6.18 µs ± 67.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

**Comment by jorisvandenbossche** [comment]
@snowman2 I don't think those timings can tell us much (or at least we should compare them with the timing before this PR). 

I did some timings on a bigger array, and also looked at how it performs when parallelizing: https://nbviewer.jupyter.org/gist/jorisvandenbossche/a97d780c04959812c40b22d6c866f4fa

So I think the conclusion from that can be that the nogil added in `_Proj._fwd` does more harm than good. 
That said, I was wondering: is there something that those `_fwd` and `_inv` methods do differently compared to Transformer? Could they use `Transformer` under the hood? Because in those methods, we iterate over the coordinates and feed them one by one to `proj_trans`, while Transformer also handles arrays of coordinates but passes them in one go as array to `proj_trans_generic`, making this easier to release the GIL.

**Comment by snowman2** [comment]
Interesting! Thanks for taking a look. I just looked at the transformer so it sounds like timing will be needed for the others for verification.

**Comment by jorisvandenbossche** [comment]
For the transformer it is fine, but for `_Proj._fwd`, I would remove it (can do a PR if you want). The geodesic one I didn't time.

**Comment by snowman2** [comment]
I will think on it. I think there is probably a way to wrap the whole loop in a nogil with some better reorganization.

**Comment by jorisvandenbossche** [comment]
See my note above about that. At least conceptually, Proj._inv/fwd seems the same as transform. Does it behave differently is some corner cases?

**Comment by snowman2** [comment]
> Could they use Transformer under the hood?

The Transformer can do essentially the same thing.  Re-directing people to use it instead of Proj is my current plan as I don't know everyone's use case to fully test the transition and mostly have Proj for backwards compatibility and don't plan on adding the same functionality. Currently, only has the original functionality.

**Comment by jorisvandenbossche** [comment]
In that case, I would personally also not do the effort to refactor that for loop to be able to wrap the fool loop in `nogil` (as such a refactor can then also change corner cases), and simply don't bother with `nogil` in this function (`transform` is faster anyway).

**Comment by snowman2** [comment]
Ha, I had the same thought after writing that. If you would like to remove the nogil stuff from Proj, that would be helpful. Thanks!

**Comment by snowman2** [comment]
It was a simple enough fix for Proj, so I added it in #446

**Pull request merged**
