### PR TITLE
add errcheck kwarg, default False so behavior is as in 1.9.6 (issue #202)

### PR DESCRIPTION
**Pull request by jswhit**
needs some docstring updates and a test.

kwarg `errcheck` argument added to transform.  Default `False` means invalid projection transform returns `inf` as in 1.9.6, instead of raising an exception.

`pyproj.Proj` already behaves this way, except 1.e30 is returned.

### CODE REVIEW

**Comment by snowman2** [comment]
Sounds like a good solution to me 👍

**Comment by snowman2** [comment]
Thoughts about raising warning if errcheck is false? Same for Proj?

**Comment by jswhit** [comment]
If tests pass, this should be ready to merge.

**Comment by jswhit** [comment]
I'm +0 on raising a warning - I personally find them annoying.

**Comment by snowman2** [comment]
Can you add numpy to requirements-dev.txt?

**Comment by snowman2** [comment]
I agree with you on the warning vote.

**Comment by snowman2** [comment]
Should a 2.1.1 release be made with this update?

**Comment by jswhit** [comment]
Yes, I think so.  Will try to do that tomorrow.

**Comment by snowman2** [comment]
Sounds good. Thanks for fixing this and taking care of the release!

**Pull request merged**
