### PR TITLE
BUG: Allow *_name to be added in CRS.to_cf

### LINKED ISSUE #585: `geographic_crs_name` missing from the CF version of a CRS
#### Code Sample, a copy-pastable example if possible

```python
from pyproj import CRS                                                                                                                
crs = CRS.from_proj4('+proj=omerc +alpha=8.998112717187938 +lat_0=0.0 +lonc=13.809602948622212 +gamma=0 +ellps=sphere')               
print(crs.to_cf())                                                                                                                           
```

#### Problem description

When using the latest cfchecker (4.0.0) on a netcdf file containing the output of `crs.to_cf`, we get an error:
```
------------------
Checking variable: oblique_mercator
------------------
INFO: (5.6): CF checker currently does not verify the syntax of the crs_wkt attribute which must conform to the CRS WKT specification
ERROR: (5.6): reference_ellipsoid_name, prime_meridian_name, horizontal_datum_name and geographic_crs_name must all be definied if any one is defined
```

Indeed, the output from `to_cf` in this case is:
```python
{'crs_wkt': 'PROJCRS["unknown",BASEGEOGCRS["unknown",DATUM["Unknown based on Normal Sphere (r=6370997) ellipsoid",ELLIPSOID["Normal Sphere (r=6370997)",6370997,0,LENGTHUNIT["metre",1,ID["EPSG",9001]]]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8901]]],CONVERSION["unknown",METHOD["Hotine Oblique Mercator (variant B)",ID["EPSG",9815]],PARAMETER["Latitude of projection centre",0,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8811]],PARAMETER["Longitude of projection centre",13.8096029486222,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8812]],PARAMETER["Azimuth of initial line",8.99811271718794,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8813]],PARAMETER["Angle from Rectified to Skew Grid",0,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8814]],PARAMETER["Scale factor on initial line",1,SCALEUNIT["unity",1],ID["EPSG",8815]],PARAMETER["Easting at projection centre",0,LENGTHUNIT["metre",1],ID["EPSG",8816]],PARAMETER["Northing at projection centre",0,LENGTHUNIT["metre",1],ID["EPSG",8817]]],CS[Cartesian,2],AXIS["(E)",east,ORDER[1],LENGTHUNIT["metre",1,ID["EPSG",9001]]],AXIS["(N)",north,ORDER[2],LENGTHUNIT["metre",1,ID["EPSG",9001]]]]',
 'semi_major_axis': 6370997.0,
 'semi_minor_axis': 6370997.0,
 'inverse_flattening': 0.0,
 'reference_ellipsoid_name': 'Normal Sphere (r=6370997)',
 'longitude_of_prime_meridian': 0.0,
 'prime_meridian_name': 'Greenwich',
 'horizontal_datum_name': 'Unknown based on Normal Sphere (r=6370997) ellipsoid',
 'grid_mapping_name': 'oblique_mercator',
 'latitude_of_projection_origin': 0.0,
 'longitude_of_projection_origin': 13.809602948622212,
 'azimuth_of_central_line': 8.998112717187938,
 'scale_factor_at_projection_origin': 1.0,
 'false_easting': 0.0,
 'false_northing': 0.0}

```

As you can see, `geographic_crs_name` is missing. As the CF document says: 
> Corresponds to a OGC WKT GEOGCS node name

and I don't see one in the wkt attached.

So in conclusion, with this projection definition, it looks like to me that the `to_cf` method isn't generating a CF compliant grid mapping.

#### Expected Output

I would expect `geographic_crs_name` to be present in the keys of the returned dict.

#### Environment Information
pyproj info:
    pyproj: 2.6.0
      PROJ: 6.3.1
  data dir: /home/a001673/miniconda3/envs/py3/lib/python3.8/site-packages/pyproj/proj_dir/share/proj

System:
    python: 3.8.2 | packaged by conda-forge | (default, Mar 23 2020, 18:16:37)  [GCC 7.3.0]
executable: /home/a001673/miniconda3/envs/py3/bin/python
   machine: Linux-4.18.0-147.5.1.el8_1.x86_64-x86_64-with-glibc2.10

Python deps:
       pip: 20.0.2
setuptools: 46.1.3.post20200325
    Cython: 0.29.14

#### Installation method
 - conda

#### Conda environment information (if you installed with conda):

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list | grep -E "proj|aenum"
proj                      6.3.1                hc80f0dc_1    conda-forge
pyproj                    2.6.0            py38h95a477d_0    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : py3
    active env location : /home/a001673/miniconda3/envs/py3
            shell level : 2
       user config file : /home/a001673/.condarc
 populated config files : /home/a001673/.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.7.4.final.0
       virtual packages : __glibc=2.28
       base environment : /home/a001673/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/a001673/miniconda3/pkgs
                          /home/a001673/.conda/pkgs
       envs directories : /home/a001673/miniconda3/envs
                          /home/a001673/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.4 Linux/4.18.0-147.5.1.el8_1.x86_64 rhel/8.1 glibc/2.28
                UID:GID : 62310:2000
             netrc file : None
           offline mode : False


```
</details>

### PR DESCRIPTION
**Pull request by mraspaud**
This add the geographic_crs_name

 - [x] Closes #585 
 - [x] Tests added
 - [x] Fully documented, including `history.rst` for all changes and `api/*.rst` for new API

### CODE REVIEW

**Comment by mraspaud** [comment]
@snowman2 I can't find `history.rst` anywhere in the repo ?

**Comment by snowman2** [comment]
Thanks for working on this - I will take a look later.

> @snowman2 I can't find `history.rst` anywhere in the repo ?

It is in `docs/history.rst`. Feel free to add the `2.6.1` header for the next release.

**Comment by snowman2** [comment]
Also, I am thinking the `unknown_names` filters in `to_cf` will need to be moved over to `from_cf` for all of the `*_name` CF attributes.

**Comment by mraspaud** [comment]
> Also, I am thinking the `unknown_names` filters in `to_cf` will need to be moved over to `from_cf` for all of the `*_name` CF attributes.

I'm not sure I understand how the unknown_names can be moved to `from_cf` as *_names are already set to "undefined" if they are not present in the cf ?

**Comment by snowman2** [comment]
I guess that was pretty vague. Hopefully this helps:

Here are the places where I filtered out adding these if they are in the `unknown_names` in the `CRS.to_cf` function:
- https://github.com/pyproj4/pyproj/blob/0cd7f67817c78d3d2b1ab89085f42e4665a26b48/pyproj/crs/crs.py#L611
- https://github.com/pyproj4/pyproj/blob/0cd7f67817c78d3d2b1ab89085f42e4665a26b48/pyproj/crs/crs.py#L622
- https://github.com/pyproj4/pyproj/blob/0cd7f67817c78d3d2b1ab89085f42e4665a26b48/pyproj/crs/crs.py#L626
- https://github.com/pyproj4/pyproj/blob/0cd7f67817c78d3d2b1ab89085f42e4665a26b48/pyproj/crs/crs.py#L640
- https://github.com/pyproj4/pyproj/blob/0cd7f67817c78d3d2b1ab89085f42e4665a26b48/pyproj/crs/crs.py#L652 

Here is where I was originally thinking the filters would need to be added for `unknown_names` (used in the `from_cf` function (anything using `from_name`). But, I think since they are secondary, they would fail anyway, so not really necessary to filter them out:
https://github.com/pyproj4/pyproj/blob/0cd7f67817c78d3d2b1ab89085f42e4665a26b48/pyproj/crs/_cf1x8.py#L36-L74

So, sounds like just removing the filters in `to_cf` is all that is needed.

**Comment by mraspaud** [comment]
Ok, thanks! That was what I gathered then :)

**Comment by snowman2** [comment]
@mraspaud, would you mind removing all the other `not in unknown_names` filters in the `to_cf` method in this PR? I think with that will be the last change to make this fully CF compliant with the portion mentioned in the issue.

**Comment by mraspaud** [comment]
I'll get at it today. I'm just wondering what to do if all *_names are undefined: just remove them all?

**Comment by mraspaud** [comment]
OK I just saw you comment on the cf issue, so I'll just leave them be.

**Comment by snowman2** [comment]
@mraspaud, this looks great :+1:. Would you like to squash your commits? Or would you be okay with me using `squash and merge`?

**Comment by mraspaud** [comment]
Yes, go ahead and squash merge! Thanks for the guidance!

**Comment by snowman2** [comment]
Perfect, thanks for the fix!

**Pull request merged**
