### PR TITLE
skip tranformation operation if input and output projections are equivalent

### PR DESCRIPTION
**Pull request by snowman2**
issue #128

### CODE REVIEW

**Comment by snowman2** [comment]
If tests pass, should be good to go if you like the implementation.

**Comment by jswhit2** [comment]
Do we really need a `skip_equivalent` keyword, or can we just always skip the transform if the projections are equivalent?

**Comment by snowman2** [comment]
I have had the same thought. My main concern is the possibility that there may be similar projections but going through with the transform would have a minor shift. So, adding the flag was my way of addressing this concern. 

If I knew that it was something I could depend on 100%, I wouldn't have any issues removing the flag.

**Comment by snowman2** [comment]
@kbevers @rouault, how safe would it be to skip transformations based on `

**Comment by snowman2** [comment]
I am hitting all kinds of wrong buttons with my phone 😛

**Comment by snowman2** [comment]
Looks like there's a strict option. https://github.com/OSGeo/proj.4/blob/4b99c3b47e76afdeda2425e39ff53fed0f12b679/src/proj.h#L543

Maybe always skip on strict with equivalent as optional?

**Comment by snowman2** [comment]
Thoughts on the updated version?

**Comment by snowman2** [comment]
Different thoughts I have:
1. If <100% sure the equivalent projections will produce the same results, keep in current form
2. If ~100% sure equivalent projections will produce the same as exact, and feeling okay about it, make `skip_equivalent` default to true.
3. 100% the equivalent projections will produce same results, remove `skip_equivalent` option and exact comparison, and skip all equivalent transformations.

I went with (1) due to my lack of knowledge/experience with all the different combinations of projections. But, feel free to fill in any missing gaps.

**Pull request merged**
