### PR TITLE
 Updated to use the CRS definition for Proj instances in transforms

### PR DESCRIPTION
**Pull request by snowman2**
#207 

The main question I have is: Why is it failing for epsg:4214 to epsg:4326 using the CRS method but works for the PROJ method?

```
pyproj.exceptions.ProjError: proj_trans_generic error: b'no system list, errno: 22\n'

```

### CODE REVIEW

**Comment by snowman2** [comment]
@rouault @kbevers any insight into the error where epsg:4214 to epsg:4326 using `proj_create_crs_to_crs` and `proj_trans_generic` fails with the error above, but converting to the PROJ string works?

Example:

```python
>>> from pyproj import *
>>> transform(4214, 4326, 30, 30, errcheck=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/snowal/scripts/pyproj/pyproj/transformer.py", line 347, in transform
    x, y, z, radians, errcheck=errcheck
  File "/home/snowal/scripts/pyproj/pyproj/transformer.py", line 169, in transform
    self._transformer._transform(inx, iny, inz, radians, errcheck=errcheck)
  File "pyproj/_transformer.pyx", line 164, in pyproj._transformer._Transformer._transform
    raise ProjError("proj_trans_generic error: {}".format(
pyproj.exceptions.ProjError: proj_trans_generic error: no system list, errno: 22
>>> proj = Proj(4214)
>>> proj.crs.to_proj4()
'+proj=longlat +ellps=krass +no_defs +type=crs'
>>> transform('+proj=longlat +ellps=krass +no_defs +type=crs', 4326, 30, 30, errcheck=True)
(30.0, 30.0)
```

**Comment by snowman2** [comment]
Looks like `nose2` reports success in the CI/CD when tests fail (see build logs). Maybe need to switch to `pytest`.

**Comment by rouault** [comment]
> @rouault @kbevers any insight into the error where epsg:4214 to epsg:4326 using `proj_create_crs_to_crs` and `proj_trans_generic` fails with the error above,

Yes, this is the same as https://github.com/OSGeo/proj.4/issues/1329 that has been fixed now. 30,30 is outside of China.

**Comment by snowman2** [comment]
Fantastic, so this is a very simple fix!

**Comment by snowman2** [comment]
Maybe I should try the most recent version of PROJ on git:
```python
>>> from pyproj import CRS
>>> crs = CRS.from_epsg(4214)
>>> crs
<CRS: epsg:4214>
Name: Beijing 1954
Ellipsoid:
- semi_major_metre: 6378245.00
- semi_minor_metre: 6356863.02
- inverse_flattening: 298.30
Area of Use:
- name: China
- bounds: (73.62, 16.7, 134.77, 53.56)
Prime Meridian:
- longitude: 0.0000
- unit_name: degree
- unit_conversion_factor: 0.01745329
Axis Info:
- Geodetic latitude[Lat] (north) EPSG:9122 (degree)
- Geodetic longitude[Lon] (east) EPSG:9122 (degree)

>>> from pyproj import transform
>>> transform(4214, 4326, 112, 30, errcheck=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/snowal/scripts/pyproj/pyproj/transformer.py", line 347, in transform
    x, y, z, radians, errcheck=errcheck
  File "/home/snowal/scripts/pyproj/pyproj/transformer.py", line 169, in transform
    self._transformer._transform(inx, iny, inz, radians, errcheck=errcheck)
  File "pyproj/_transformer.pyx", line 160, in pyproj._transformer._Transformer._transform
    raise ProjError("proj_trans_generic error: {}".format(
pyproj.exceptions.ProjError: proj_trans_generic error: no system list, errno: 22
```

**Comment by snowman2** [comment]
Yep, the new version works: https://travis-ci.org/pyproj4/pyproj/jobs/508894736

**Comment by snowman2** [comment]
@jswhit, since the failing tests are related to upstream issues, I think this PR is ready to go pending your review.

**Comment by snowman2** [comment]
Also @jswhit, after merging, should we make a 2.1.2 release with this fix?

**Comment by snowman2** [comment]
Ah, just noticed the review approval. Should be good to go then.

**Comment by snowman2** [comment]
All tests pass on the new PROJ version: https://travis-ci.org/pyproj4/pyproj/jobs/508937788

**Comment by jswhit** [comment]
> Also @jswhit, after merging, should we make a 2.1.2 release with this fix?

I'll wait till the weekend and see if anything else comes up.

**Comment by snowman2** [comment]
Sounds like a good plan to me 👍

**Pull request merged**
