### PR TITLE
embedsignature is a Cython compiler directive

### PR DESCRIPTION
**Pull request by cjmayo**
Also fixes a warning:
```
/usr/lib/python3.7/distutils/extension.py:131: UserWarning: Unknown Extension options: 'embedsignature'
```
and gets introspection working in ipython. It does fill in missing annotations in html docs when you rebuild them, but the way Cython does it isn't always ideal e.g. including `self` in class method signatures.

```diff
--- a/docs/html/api/crs.html
+++ b/docs/html/api/crs.html
@@ -218,7 +218,7 @@ about specifying projection parameters.</p>
 
 <dl class="method">
 <dt id="pyproj.crs.CRS.is_exact_same">
-<code class="descname">is_exact_same</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#pyproj.crs.CRS.is_exact_same" title="Permalink to this definition">¶</a></dt>
+<code class="descname">is_exact_same</code><span class="sig-paren">(</span><em>self</em>, <em>_CRS other</em><span class="sig-paren">)</span><a class="headerlink" href="#pyproj.crs.CRS.is_exact_same" title="Permalink to this definition">¶</a></dt>
 <dd><p>Compares projections to see if they are exactly the same.</p>
 </dd></dl>
 
@@ -250,6 +250,17 @@ about specifying projection parameters.</p>
 :rtype: True if projection is a valid type.</p>
 </dd></dl>
 
+<dl class="attribute">
+<dt id="pyproj.crs.CRS.name">
+<code class="descname">name</code><a class="headerlink" href="#pyproj.crs.CRS.name" title="Permalink to this definition">¶</a></dt>
+<dd><p>object</p>
+<dl class="field-list simple">
+<dt class="field-odd">Type</dt>
+<dd class="field-odd"><p>name</p>
+</dd>
+</dl>
+</dd></dl>
+
 <dl class="attribute">
 <dt id="pyproj.crs.CRS.prime_meridian">
 <code class="descname">prime_meridian</code><a class="headerlink" href="#pyproj.crs.CRS.prime_meridian" title="Permalink to this definition">¶</a></dt>
@@ -257,9 +268,31 @@ about specifying projection parameters.</p>
 :rtype: The CRS prime meridian object with associated attributes.</p>
 </dd></dl>
 
+<dl class="attribute">
+<dt id="pyproj.crs.CRS.proj_version">
+<code class="descname">proj_version</code><a class="headerlink" href="#pyproj.crs.CRS.proj_version" title="Permalink to this definition">¶</a></dt>
+<dd><p>object</p>
+<dl class="field-list simple">
+<dt class="field-odd">Type</dt>
+<dd class="field-odd"><p>proj_version</p>
+</dd>
+</dl>
+</dd></dl>
+
+<dl class="attribute">
+<dt id="pyproj.crs.CRS.srs">
+<code class="descname">srs</code><a class="headerlink" href="#pyproj.crs.CRS.srs" title="Permalink to this definition">¶</a></dt>
+<dd><p>object</p>
+<dl class="field-list simple">
+<dt class="field-odd">Type</dt>
+<dd class="field-odd"><p>srs</p>
+</dd>
+</dl>
+</dd></dl>
+
 <dl class="method">
 <dt id="pyproj.crs.CRS.to_epsg">
-<code class="descname">to_epsg</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#pyproj.crs.CRS.to_epsg" title="Permalink to this definition">¶</a></dt>
+<code class="descname">to_epsg</code><span class="sig-paren">(</span><em>self</em>, <em>min_confidence=70</em><span class="sig-paren">)</span><a class="headerlink" href="#pyproj.crs.CRS.to_epsg" title="Permalink to this definition">¶</a></dt>
 <dd><p>Return the EPSG code best matching the projection.</p>
 <dl class="field-list simple">
 <dt class="field-odd">Parameters</dt>
@@ -276,7 +309,7 @@ about specifying projection parameters.</p>
 
 <dl class="method">
 <dt id="pyproj.crs.CRS.to_geodetic">
-<code class="descname">to_geodetic</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#pyproj.crs.CRS.to_geodetic" title="Permalink to this definition">¶</a></dt>
+<code class="descname">to_geodetic</code><span class="sig-paren">(</span><em>self</em><span class="sig-paren">)</span><a class="headerlink" href="#pyproj.crs.CRS.to_geodetic" title="Permalink to this definition">¶</a></dt>
 <dd><dl class="field-list simple">
 <dt class="field-odd">Returns</dt>
 <dd class="field-odd"><p><strong>pyproj.CRS</strong></p>
@@ -289,7 +322,7 @@ about specifying projection parameters.</p>
 
 <dl class="method">
 <dt id="pyproj.crs.CRS.to_proj4">
-<code class="descname">to_proj4</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#pyproj.crs.CRS.to_proj4" title="Permalink to this definition">¶</a></dt>
+<code class="descname">to_proj4</code><span class="sig-paren">(</span><em>self</em>, <em>version=4</em><span class="sig-paren">)</span><a class="headerlink" href="#pyproj.crs.CRS.to_proj4" title="Permalink to this definition">¶</a></dt>
 <dd><p>Convert the projection to a proj.4 string.</p>
 <dl class="field-list simple">
 <dt class="field-odd">Parameters</dt>
@@ -306,7 +339,7 @@ about specifying projection parameters.</p>
 
 <dl class="method">
 <dt id="pyproj.crs.CRS.to_wkt">
-<code class="descname">to_wkt</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#pyproj.crs.CRS.to_wkt" title="Permalink to this definition">¶</a></dt>
+<code class="descname">to_wkt</code><span class="sig-paren">(</span><em>self</em>, <em>version=u'WKT2_2018'</em><span class="sig-paren">)</span><a class="headerlink" href="#pyproj.crs.CRS.to_wkt" title="Permalink to this definition">¶</a></dt>
 <dd><p>Convert the projection to a WKT string.</p>
 <dl class="simple">
 <dt>Version options:</dt><dd><ul class="simple">
@@ -339,7 +372,7 @@ about specifying projection parameters.</p>
 <h2>pyproj.crs.is_wkt<a class="headerlink" href="#pyproj-crs-is-wkt" title="Permalink to this headline">¶</a></h2>
 <dl class="function">
 <dt id="pyproj.crs.is_wkt">
-<code class="descclassname">pyproj.crs.</code><code class="descname">is_wkt</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#pyproj.crs.is_wkt" title="Permalink to this definition">¶</a></dt>
+<code class="descclassname">pyproj.crs.</code><code class="descname">is_wkt</code><span class="sig-paren">(</span><em>proj_string</em><span class="sig-paren">)</span><a 
```

```diff
--- a/docs/html/api/geod.html
+++ b/docs/html/api/geod.html
@@ -162,6 +162,50 @@ users manual).</p>
 </div>
 </dd></dl>
 
+<dl class="attribute">
+<dt id="pyproj.Geod.a">
+<code class="descname">a</code><a class="headerlink" href="#pyproj.Geod.a" title="Permalink to this definition">¶</a></dt>
+<dd><p>object</p>
+<dl class="field-list simple">
+<dt class="field-odd">Type</dt>
+<dd class="field-odd"><p>a</p>
+</dd>
+</dl>
+</dd></dl>
+
+<dl class="attribute">
+<dt id="pyproj.Geod.b">
+<code class="descname">b</code><a class="headerlink" href="#pyproj.Geod.b" title="Permalink to this definition">¶</a></dt>
+<dd><p>object</p>
+<dl class="field-list simple">
+<dt class="field-odd">Type</dt>
+<dd class="field-odd"><p>b</p>
+</dd>
+</dl>
+</dd></dl>
+
+<dl class="attribute">
+<dt id="pyproj.Geod.es">
+<code class="descname">es</code><a class="headerlink" href="#pyproj.Geod.es" title="Permalink to this definition">¶</a></dt>
+<dd><p>object</p>
+<dl class="field-list simple">
+<dt class="field-odd">Type</dt>
+<dd class="field-odd"><p>es</p>
+</dd>
+</dl>
+</dd></dl>
+
+<dl class="attribute">
+<dt id="pyproj.Geod.f">
+<code class="descname">f</code><a class="headerlink" href="#pyproj.Geod.f" title="Permalink to this definition">¶</a></dt>
+<dd><p>object</p>
+<dl class="field-list simple">
+<dt class="field-odd">Type</dt>
+<dd class="field-odd"><p>f</p>
+</dd>
+</dl>
+</dd></dl>
+
 <dl class="method">
 <dt id="pyproj.Geod.fwd">
 <code class="descname">fwd</code><span class="sig-paren">(</span><em>lons</em>, <em>lats</em>, <em>az</em>, <em>dist</em>, <em>radians=False</em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/pyproj/geod.html#Geod.fwd"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#pyproj.Geod.fwd" title="Permalink to this definition">¶</a></dt>
@@ -177,6 +221,17 @@ sequences and scalars.</p>
 degrees. Distances are in meters.</p>
 </dd></dl>
 
+<dl class="attribute">
+<dt id="pyproj.Geod.initstring">
+<code class="descname">initstring</code><a class="headerlink" href="#pyproj.Geod.initstring" title="Permalink to this definition">¶</a></dt>
+<dd><p>object</p>
+<dl class="field-list simple">
+<dt class="field-odd">Type</dt>
+<dd class="field-odd"><p>initstring</p>
+</dd>
+</dl>
+</dd></dl>
+
 <dl class="method">
 <dt id="pyproj.Geod.inv">
 <code class="descname">inv</code><span class="sig-paren">(</span><em>lons1</em>, <em>lats1</em>, <em>lons2</em>, <em>lats2</em>, <em>radians=False</em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/pyproj/geod.html#Geod.inv"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#pyproj.Geod.inv" title="Permalink to this definition">¶</a></dt>
@@ -237,6 +292,17 @@ terminus points.</p>
 </div>
 </dd></dl>
 
+<dl class="attribute">
+<dt id="pyproj.Geod.sphere">
+<code class="descname">sphere</code><a class="headerlink" href="#pyproj.Geod.sphere" title="Permalink to this definition">¶</a></dt>
+<dd><p>object</p>
+<dl class="field-list simple">
+<dt class="field-odd">Type</dt>
+<dd class="field-odd"><p>sphere</p>
+</dd>
+</dl>
+</dd></dl>
+
 </dd></dl>
 ```

### CODE REVIEW

**Comment by snowman2** [comment]
Nice fix. Thanks! Approved from my end.

**Comment by snowman2** [comment]
> Why is os.name != nt needed?

I had an issue with it - which this probably solves. Maybe we should test removing it.

**Comment by cjmayo** [comment]
Now without `os.name != nt`. (I'm only testing on Linux).

**Comment by snowman2** [comment]
Looks like it was successful with os.name removed. Thanks @cjmayo!

**Comment by snowman2** [comment]
@jswhit, any blockers for merging on your end?

**Comment by snowman2** [comment]
Thanks for the review @jswhit!

**Pull request merged**
