### PR TITLE
CI: pin pip < 19.1 to avoid breakage of editable install

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Alternative / easier, temporary fix for https://github.com/pyproj4/pyproj/pull/282 by just pinning pip, since they are still discussing whether to fix this on the pip side (https://github.com/pypa/pip/issues/6434)

### CODE REVIEW

**Comment by snowman2** [comment]
This seems like a nice solution if editable is required.

**Comment by jorisvandenbossche** [comment]
Argh, now appveyor is failing for some reason ...

```
Executing: pip install "pip>=10.0.1,<19.1"
Collecting pip<19.1,>=10.0.1
  Downloading https://files.pythonhosted.org/packages/d8/f3/413bab4ff08e1fc4828dfc59996d721917df8e8583ea85385d51125dceff/pip-19.0.3-py2.py3-none-any.whl (1.4MB)
Installing collected packages: pip
  Found existing installation: pip 19.1
    Uninstalling pip-19.1:
      Successfully uninstalled pip-19.1
  Rolling back uninstall of pip
  Moving to c:\users\appveyor\appdata\roaming\python\python36\scripts\
   from c:\users\appveyor\appdata\roaming\python\python36\~cripts
  Moving to c:\users\appveyor\appdata\roaming\python\python36\site-packages\pip-19.1.dist-info\
   from c:\users\appveyor\appdata\roaming\python\python36\site-packages\~ip-19.1.dist-info
  Moving to c:\users\appveyor\appdata\roaming\python\python36\site-packages\pip\
   from c:\users\appveyor\appdata\roaming\python\python36\site-packages\~ip
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\appveyor\AppData\Roaming\Python\Python36\site-packages\pip\_internal\cli\base_command.py", line 178, in main
    status = self.run(options, args)
  File "C:\Users\appveyor\AppData\Roaming\Python\Python36\site-packages\pip\_internal\commands\install.py", line 414, in run
    use_user_site=options.use_user_site,
  File "C:\Users\appveyor\AppData\Roaming\Python\Python36\site-packages\pip\_internal\req\__init__.py", line 58, in install_given_reqs
    **kwargs
  File "C:\Users\appveyor\AppData\Roaming\Python\Python36\site-packages\pip\_internal\req\req_install.py", line 922, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "C:\Users\appveyor\AppData\Roaming\Python\Python36\site-packages\pip\_internal\req\req_install.py", line 448, in move_wheel_files
    warn_script_location=warn_script_location,
  File "C:\Users\appveyor\AppData\Roaming\Python\Python36\site-packages\pip\_internal\wheel.py", line 544, in move_wheel_files
    generated.extend(maker.make(spec))
  File "C:\Users\appveyor\AppData\Roaming\Python\Python36\site-packages\pip\_vendor\distlib\scripts.py", line 405, in make
    self._make_script(entry, filenames, options=options)
  File "C:\Users\appveyor\AppData\Roaming\Python\Python36\site-packages\pip\_vendor\distlib\scripts.py", line 309, in _make_script
    self._write_script(scriptnames, shebang, script, filenames, ext)
  File "C:\Users\appveyor\AppData\Roaming\Python\Python36\site-packages\pip\_vendor\distlib\scripts.py", line 245, in _write_script
    launcher = self._get_launcher('t')
  File "C:\Users\appveyor\AppData\Roaming\Python\Python36\site-packages\pip\_vendor\distlib\scripts.py", line 384, in _get_launcher
    result = finder(distlib_package).find(name).bytes
AttributeError: 'NoneType' object has no attribute 'bytes'
```

**Comment by jorisvandenbossche** [comment]
That error is typically encountered if pip was installed as an egg (https://github.com/pypa/pip/issues/5820), however that does not seem to be the case here. But trying to pin more (it is installed in two places, which is probably not needed)

**Comment by jorisvandenbossche** [comment]
@snowman2 ok this is passing now. I think it would be good to merge this (awaiting a more long term solution), as it is holding updating the other PRs

**Comment by snowman2** [comment]
Looks good to me.  Thanks @jorisvandenbossche!

@jswhit since this is a minor fix and all other builds will be broken until this is in, I am merging now.

**Pull request merged**
