### PR TITLE
PERF: thread local context

### LINKED ISSUE #1133: PERF: Thread-local global contex
From: https://github.com/shapely/shapely/issues/1523#issuecomment-1237347057

Sounds like a good idea to look into seeing if https://docs.python.org/3/c-api/init.html#thread-local-storage-support would allow always using a thead-local global context instead of enabling a single global version (https://pyproj4.github.io/pyproj/stable/api/global_context.html).

Also see:
- https://peps.python.org/pep-0539/
- https://github.com/cython/cython/blob/efdf996dced075682d86b7e53a12b56b5ebfea38/tests/run/tss.pyx

### PR DESCRIPTION
**Pull request by snowman2**
- [x] Closes #1133
 - [ ] Tests added
 - [ ] Fully documented, including `history.rst` for all changes and `api/*.rst` for new API

TODO: Thread local proj error message

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
This is interesting! 
The pythread APIs require cython 3 alpha?

**Comment by snowman2** [comment]
> The pythread APIs require cython 3 alpha?

I believe so.
- https://github.com/cython/cython/commit/07115e3f547f9e375e64488e79bca12b45bd08bd 
- https://github.com/cython/cython/commit/8fab3aabe93c3c60b0084f30fdff6d4fd1e37b42

**Comment by snowman2** [comment]
The part I haven't found a good solution for is de-allocating the context when the thread is removed. The current solution doesn't seem to be stable.

**Comment by jorisvandenbossche** [comment]
Both those commits you reference are also included in 0.29.x, it seems (if you expand the list of tags in the github UI)

**Comment by snowman2** [comment]
> Both those commits you reference are also included in 0.29.x, it seems (if you expand the list of tags in the github UI)

Looks like you are correct. Thanks 👍
Screenshot_20220920-071108

**Comment by snowman2** [comment]
This seems to be fairly stable. @jorisvandenbossche if you have time to test this out with dask-geopandas, I would appreciate it.

**Comment by snowman2** [comment]
Downside to this approach is every time you create a thread, a new context is created that is not deleted until the program exits:
```
def test_crs_multithread():
    # https://github.com/pyproj4/pyproj/issues/782
    crs = CRS(4326)

    def to_wkt(num):
        crs.to_wkt()
        return CRS(4326)

    with concurrent.futures.ThreadPoolExecutor(max_workers=100) as executor:
        for result in executor.map(to_wkt, range(10000)):
            result.to_wkt()

    with concurrent.futures.ThreadPoolExecutor(max_workers=100) as executor:
        for result in executor.map(to_wkt, range(10000)):
            result.to_wkt()
```
Leads to a context count: 201

**Comment by jorisvandenbossche** [comment]
Yeah, I don't know how that works if you use the C API (how you can detect that a thread gets terminated). I think the `threading.local` python API does that for you, though? (the approach you are using to make CRS thread-safe)

Would there be a way to use threading.local here as well? Although from a quick look, the thread local CRS handling is done in Python, where the python CRS class basically holds a thread local cython _CRS class. But for the PROJ context, it's the cython code that needs access to the local context, so this needs to be done in cython, not Python (I don't know if it would be possible/acceptable to introduce some python overhead in accessing the context in the cython classes)

**Comment by snowman2** [comment]
> Would there be a way to use threading.local here as well?

Thanks for taking a moment to share your thoughts on this. The first commit of this PR uses the threading.local approach. It wasn't very stable on pypy in the CI. I am not entirely sure why, but I saw some core dumping. On hypothesis I have is that it has to do with `PJ*` persisting after the thread closes pointing to the thread-specific context, but I am not sure.

Potential ideas to get the threading.local to work:
- Always call `proj_assign_context` to use the context in the current thread before using any `PROJ` method on a `PJ*` object to be sure that it is always using the context in that thread. This would change quite a bit of code and may have performance penalties.
- Wrap all cython objecs using a `PJ*` and `PJ_CONTEXT*` pointer the same way we did the CRS class and use `proj_clone` along with `proj_assign_context` to construct new objects in each thread.

**Comment by snowman2** [comment]
Found a better way - just attach the context manager to each object that uses it. Then, once all references to the object are removed, it deletes the context. This ensures that the thread generated contexts persists as long as it needs to and that it is cleaned up as soon as it is no longer needed.

**Pull request closed without merging**
