### PR TITLE
make testing fail on transformer docstring test failures

### PR DESCRIPTION
**Pull request by cjmayo**

### CODE REVIEW

**Comment by snowman2** [comment]
Thanks for the fix. The failures are expected (see #202). Mind checking if the proj version == 6.0.0, the error count in transforms docs is 2, otherwise 0?

**Comment by cjmayo** [comment]
May well be the same problem I was fixing with #222.

**Comment by snowman2** [comment]
Maybe cherry-pick that commit into this PR?

**Comment by snowman2** [comment]
Thanks @cjmayo!

**Pull request merged**
