### PR TITLE
update version to 2.2.2; add PROJ version in wheel update in history

### PR DESCRIPTION
**Pull request by snowman2**
I can't think of anything else that should be included in this release. 
@jswhit @jorisvandenbossche @micahcochran any reasons to delay the release?

### CODE REVIEW

**Comment by snowman2** [comment]
Only concern is mentioned in #358 and its potential impact with geopandas users.

**Comment by jorisvandenbossche** [comment]
> Only concern is mentioned in #355 and its potential impact with geopandas users.

You changed the warning to a DeprecationWarning, correct? In that case, I think end users should not yet see it if it is still used in geopandas (we should still fix it though)

**Comment by snowman2** [comment]
> You changed the warning to a DeprecationWarning, correct?

Actually it is a `FutureWarning` at the moment. I think changing it to a `DeprecationWarning` would probably be better for now for the sake of #355.

**Comment by snowman2** [comment]
But, users will see a DeprecationWarning in an `ipython` console. This means it will also show up in a jupyter notebook? That is definitely still problematic.

```python
In [1]: import warnings                                                        

In [2]: warnings.warn("test", DeprecationWarning)                              
/home/snowal/miniconda3/envs/goldfinger/bin/ipython:1: DeprecationWarning: test
  #!/home/snowal/miniconda3/envs/goldfinger/bin/python

```

**Comment by jorisvandenbossche** [comment]
Ah, yes DeprecationWarning instead of FutureWarning would make sense. 
If it raised from functionality being used within a function you are using, the warning shoud not appear then.

**Comment by snowman2** [comment]
I tested it out, and it appears that a DeprecationWarning still appears when wrapped in a function:
```python
In [1]: from pyproj import CRS                                                  

In [2]: crs = CRS("epsg:4326")                                                  

In [3]: crs.to_geodetic()                                                       
/home/snowal/miniconda3/envs/pyproj/bin/ipython:1: DeprecationWarning: This method is deprecated an has been replaced with `CRS.geodetic_crs`.
  #!/home/snowal/miniconda3/envs/pyproj/bin/python
Out[3]: 
<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [5]: def geodetic(): 
   ...:     return crs.to_geodetic() 
   ...:                                                                         

In [6]: geodetic()                                                              
/home/snowal/miniconda3/envs/pyproj/bin/ipython:2: DeprecationWarning: This method is deprecated an has been replaced with `CRS.geodetic_crs`.
  
Out[6]: 
<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

```

**Comment by jorisvandenbossche** [comment]
I *think* that is because the function is still defined within IPython. If you write to a file, I don't see a warning:

```
In [18]: %%writefile test_warning.py 
    ...:  
    ...: import warnings 
    ...:  
    ...: def deprecated(): 
    ...:     warnings.warn('deprecated', DeprecationWarning) 
    ...:                                                                                                                                                      
Writing test_warning.py                                                                                                              

In [19]: test_warning.deprecated()                                                                                                                            
...

**Comment by snowman2** [comment]
I tested the Deprecation Warning in geopandas and I didn't see it. I made the change to use a DeprecationWarning. In pyproj 2.3.x I think I will change it to a Future Warning.

**Comment by snowman2** [comment]
Unless I hear otherwise, I plan to make a release tomorrow sometime.

**Pull request merged**
