### PR TITLE
made enumeration lookup case insensitive

### LINKED ISSUE #301: Make enums case insensitive
Preserves pre-existing behavior.
https://github.com/pyproj4/pyproj/pull/300#discussion_r284097494

### PR DESCRIPTION
**Pull request by snowman2**
Closes #301

@jorisvandenbossche

### CODE REVIEW

**Comment by snowman2** [comment]
The strange thing is that the Windows build is not finding aenum. It's a shame as it is nice to have.

**Comment by jorisvandenbossche** [comment]
> The strange thing is that the Windows build is not finding aenum. It's a shame as it is nice to have.

It might be related to the pip install command (as there are for sure universal wheels for all platforms/python versions). The `--no-index` maybe?

**Comment by snowman2** [comment]
> The --no-index maybe?

Maybe, definitely worth looking into.

**Comment by snowman2** [comment]
I didn't look at the full logs earlier - the failure was after the tests. Thanks for the tip @jorisvandenbossche!

**Comment by hobu** [comment]
Can aenum be made optional? It causes some complications for packagers https://lists.debian.org/debian-gis/2019/06/msg00000.html

**Pull request merged**
