### PR TITLE
Update data directory functionality

### PR DESCRIPTION
**Pull request by snowman2**
- look in PATH for data directory #176
- support multiple data directories #199
- use functions in setup.py to logically divide functionality (from old windows wheel attempts that were lost)

### CODE REVIEW

**Comment by jswhit** [comment]
What's the use case for this?  A user with multiple data directories that wants to switch back and forth?

**Comment by snowman2** [comment]
I was thinking along the lines of a user who does not have permissions to the main data directory who wanted to add datumgrids.

**Comment by jswhit2** [comment]
> I was thinking along the lines of a user who does not have permissions to the main data directory who wanted to add datumgrids.

OK, that makes sense.

**Comment by micahcochran** [comment]
> use functions in setup.py to logically divide functionality (from old windows wheel attempts that were lost)
@snowman2 That is a big improvement to setup.py.

**Comment by snowman2** [comment]
@jswhit it should be ready for a final review.

**Comment by jswhit** [comment]
Do you want this to be in the 2.1.2 release?  If so, go ahead and merge.  If not, I'll release 2.1.2 this weekend and we can merge after.

**Comment by snowman2** [comment]
I merged it in, thanks for the reviews!

**Pull request merged**
